apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: acta-prod
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/AppActa/acta-platform.git
    targetRevision: main
    path: apps

  destination:
    server: https://kubernetes.default.svc
    namespace: acta-prod

  # a versão atual do operador remove o bloco antigo syncConfig
  ignoreDifferences:
    - group: secrets.infisical.com
      kind: InfisicalSecret
      jsonPointers:
        - /spec/syncConfig

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
