apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret

metadata:
  name: acta-import-api-secrets

spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60

  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: acta-prod
      secretsScope:
        projectId: 051dcf5e-00ed-4d46-8b36-baad0a621f5d
        envSlug: prod
        secretsPath: /import-api
        recursive: false

  managedKubeSecretReferences:
    - secretName: acta-import-api-env
      secretNamespace: acta-prod
      creationPolicy: Owner

      template:
        includeAllSecrets: false
        data:
          DB_URL: "{{ .DB_URL.Value }}"
          CLOUDINARY_CLOUD_NAME: "{{ .CLOUDINARY_CLOUD_NAME.Value }}"
          CLOUDINARY_API_KEY: "{{ .CLOUDINARY_API_KEY.Value }}"
          CLOUDINARY_API_SECRET: "{{ .CLOUDINARY_API_SECRET.Value }}"
          ACTA_PG_API_URL: "{{ .ACTA_PG_API_URL.Value }}"
          ACTA_IA_TOKEN: "{{ .ACTA_IA_TOKEN.Value }}"
          REDIS_HOST: "{{ .REDIS_HOST.Value }}"
          REDIS_PORT: "{{ .REDIS_PORT.Value }}"
          REDIS_DB: "{{ .REDIS_DB.Value }}"
          REDIS_PASSWORD: "{{ .REDIS_PASSWORD.Value }}"