apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret

metadata:
  name: acta-mongo-api-secrets

spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60

  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: acta-prod
      secretsScope:
        projectId: 051dcf5e-00ed-4d46-8b36-baad0a621f5d
        envSlug: prod
        secretsPath: /mongo-api
        recursive: false

  managedKubeSecretReferences:
    - secretName: acta-mongo-api-env
      secretNamespace: acta-prod
      creationPolicy: Owner

      template:
        includeAllSecrets: false
        data:
          PORT: "{{ .PORT.Value }}"
          MONGODB_URI: "{{ .MONGODB_URI.Value }}"
          ACTA_PG_API_BASE_URL: "{{ .ACTA_PG_API_BASE_URL.Value }}"
          ACTA_PG_API_CONNECT_TIMEOUT: "{{ .ACTA_PG_API_CONNECT_TIMEOUT.Value }}"
          ACTA_PG_API_READ_TIMEOUT: "{{ .ACTA_PG_API_READ_TIMEOUT.Value }}"