apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret

metadata:
  name: acta-pg-api-secrets

spec:
  hostAPI: https://app.infisical.com/api

  syncConfig:
    resyncInterval: 60s
    instantUpdates: false

  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: acta-prod
      secretsScope:
        projectId: 051dcf5e-00ed-4d46-8b36-baad0a621f5d
        envSlug: prod
        secretsPath: /pg-api
        recursive: false

  managedKubeSecretReferences:
    - secretName: acta-pg-api-env
      secretNamespace: acta-prod
      creationPolicy: Owner

      template:
        includeAllSecrets: false
        data:
          DB_URL: "{{ .DB_URL.Value }}"
          DB_USER: "{{ .DB_USER.Value }}"
          DB_PASSWORD: "{{ .DB_PASSWORD.Value }}"
          FIREBASE_PROJECT_ID: "{{ .FIREBASE_PROJECT_ID.Value }}"
          CORS_ALLOWED_ORIGINS: "{{ .CORS_ALLOWED_ORIGINS.Value }}"

    - secretName: firebase-admin
      secretNamespace: acta-prod
      creationPolicy: Owner

      template:
        includeAllSecrets: false
        data:
          service-account.json: "{{ .FIREBASE_SERVICE_ACCOUNT_JSON.Value }}"
