apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: acta-prod

resources:
  - pg-api.yaml
  - mongo-api.yaml
  - import-api.yaml
  - config/pg-api-secrets.yaml
  - config/mongo-api-secrets.yaml
  - config/import-api-secrets.yaml